// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NavigateStraight
{
    internal sealed partial class Vsix
    {
        public const string Id = "NavigateStraight.1832fb0f-c7d9-4a37-88ad-f9dc9455f87c";
        public const string Name = "NavigateStraight";
        public const string Description = @"Navigates straight to class definition ignoring any generated files.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Marcin Kotas";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
